### ISSUE TITLE
React.PropTypes

### ISSUE THREAD

**Issue by stallter4** [react-z/react-tab-view#6]
getting the following console warning, I believe due to this component.  Do you have any plans to update it?

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by stallter4** [comment]
I love this little component, it has served me very well.  I hope you will update this to the new standard for proptypes so it can be used in React v16.

**Comment by svnm** [comment]
Sorry for being late on this, but its all done now, using latest version of react, and updated tests as well as styles with styled components
